package abapci.feature;

public enum FeatureType {
	UNIT_RUN_CRITICAL_TESTS, UNIT_RUN_DANGEROUS_TESTS, UNIT_RUN_HARMLESS_TESTS, UNIT_RUN_DURATION_LONG_TESTS, UNIT_RUN_DURATION_MEDIUM_TESTS, UNIT_RUN_DURATION_SHORT_TESTS
}
