package abapci.domain;

public enum UiTheme {
	STANDARD_THEME, 
	LIGHT_RED_THEME, 
	RED_THEME, 
	LIGHT_YELLOW_THEME, 
	YELLOW_THEME, 
	LIGHT_GREEN_THEME, 
	GREEN_THEME, 
	LIGHT_BLUE_THEME, 
	BLUE_THEME, 
	LIGHT_GRAY_THEME,
	GRAY_THEME, 
	LIGHT_ORANGE_THEME, 
	ORANGE_THEME,
	BLACK_THEME, 
	WHITE_THEME
}
